plugins {
    id 'java-library'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.springframework.boot' version '4.1.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:4.1.0'
    }
    dependencies {
        dependency 'io.github.classgraph:classgraph:4.8.184'
        dependency 'org.apache.commons:commons-csv:1.14.1'
    }
}

dependencies {
    implementation 'io.github.classgraph:classgraph'
    implementation 'org.apache.commons:commons-csv'
    implementation 'org.apache.commons:commons-lang3'
    implementation 'jakarta.annotation:jakarta.annotation-api'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'tools.jackson.core:jackson-databind'
    implementation 'tools.jackson.dataformat:jackson-dataformat-yaml'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'net.jqwik:jqwik:1.10.1'
}
